sudo: required
dist: trusty
language: cpp
compiler: gcc
install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/15.12/ trusty/"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes ragel protobuf-compiler libprotobuf-dev liberasurecode-dev attr libattr1 libattr1-dev
  - pip install --upgrade pip cpplint
script:
  - set -e
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/oio -DCMAKE_BUILD_TYPE=Release -DSYS=OFF .
  - make all
  - make -C tests/unit test
  - echo make -C tests/func test
