sudo: required
dist: trusty
language: cpp
compiler: gcc
install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/15.12/ trusty/"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libprotobuf-dev
script:
  - CMAKE_OPTS="-DCMAKE_INSTALL_PREFIX=/tmp/oio"
  - CMAKE_OPTS="$CMAKE_OPTS -DLD_LIBDIR=lib"
  - CMAKE_OPTS="$CMAKE_OPTS -DCMAKE_BUILD_TYPE=Release"
  - CMAKE_OPTS="$CMAKE_OPTS -DGTEST_SYSTEM=OFF  -DGTEST_GUESS=OFF"
  - CMAKE_OPTS="$CMAKE_OPTS -DGFLAGS_SYSTEM=OFF -DGFLAGS_GUESS=OFF"
  - CMAKE_OPTS="$CMAKE_OPTS -DGLOG_SYSTEM=OFF   -DGLOG_GUESS=OFF"
  - cmake $CMAKE_OPTS .
  - make all
  - make -C tests/unit test
  - make -C tests/func test

