sudo: required
dist: trusty
language: cpp
compiler: gcc
install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/15.12/ trusty/"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes git cmake make
  - sudo apt-get install -y --force-yes ragel libprotobuf-dev liberasurecode-dev
before_script:
  - set -e
  - git submodule init
  - git submodule update
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/oio -DLD_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DGTEST_SYSTEM=OFF -DGTEST_GUESS=OFF -DGFLAGS_SYSTEM=OFF -DGFLAGS_GUESS=OFF -DGLOG_SYSTEM=OFF -DGLOG_GUESS=OFF -DMILL_SYSTEM=OFF -DMILL_GUESS=OFF -DEC_SYSTEM=OFF -DEC_GUESS=ON .
script:
  - set -e
  - git submodule init
  - make all
  - make -C tests/unit test
  - make -C tests/func test
